### ISSUE TITLE
用了 V2 之后路由器过一会就会崩溃假死，需要重启。。。

### ISSUE THREAD

**Issue by bearcolin** [clangcn/game-server#3]
如题，根据使用强度不同发生的时机也不同。如果不怎么用的话估计能撑几个小时，如果开着打游戏可能就几十分钟就会崩溃。如果实在路由器 web 设置界面来回跳转次数多了的话可能会瞬间崩溃。
路由器是 R7000，当前系统版本7.2，SS 版本3.3.3。
之前路由器是7.4，SS 版本3.3.7，都先后降级了还是有问题。

**Comment by Joney0210** [comment]
我還想著來提issues, 你這問題都二十天了沒有回覆, 看來是沒有人管理了. 

我沒有遇到V2崩潰的情況, 主要是斷線, 不定時的. 同時派對不會斷, 所以V2應該沒有崩潰. 

請問你所述路由器假死的情況, 有沒有在路由器上開虛擬內存? V2在小寶之前帖子中, 明確要求需要開啓虛擬內存. 雖然開了從來都顯示使用量零, 但似乎是有這個需要的.

**Comment by clangcn** [comment]
这个v2暂时不更新了，我也是在等大神更新v3

**Comment by bearcolin** [comment]
@Joney0210 一开始没开虚拟内存崩溃，后来开了之后也还是一样崩溃，并没有明显缓解。
