### ISSUE TITLE
kip-server init 似乎沒有安裝

### ISSUE THREAD

**Issue by Joney0210** [clangcn/game-server#4]
不知道有沒有影响,但在LOG檔中看到 /etc/init.d/kcp-server . 但實際該目錄中沒有該文件.
是不是安裝不完全呢? 但是在game-server-install.log 中又沒有看到安裝KCP的部份.

`root@xxxxxx:~# ./install-game-server.sh update

#####################################################################
# Install Game-Server(XiaoBao) for CentOS Debian or Ubuntu(32/64bit)
# Intro: http://clang.cn
# Author: Clang <admin@clangcn.com>
# Version 6.0
#####################################################################

curl 7.38.0 (x86_64-pc-linux-gnu) libcurl/7.38.0 OpenSSL/1.0.1t zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API SPNEGO NTLM NTLM_WB SSL libz TLS-SRP
 Run curl success

curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
============== Update Game-Server(XiaoBao) install shell ==============
============== Update Game-Server(XiaoBao) ==============
game-server: no process found
sed: can't read /etc/init.d/kcp-server: No such file or directory
========== Update kcp-Server(XiaoBao) /etc/init.d/game-server ==========
converted 'https://raw.githubusercontent.com/clangcn/game-server/master/init/game-server.init' (ANSI_X3.4-1968) -> 'https://raw.githubusercontent.com/clangcn/game-server/master/init/game-server.init' (UTF-8)
--2017-04-28 14:00:00--  https://raw.githubusercontent.com/clangcn/game-server/master/init/game-server.init
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.76.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.76.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2622 (2.6K) [text/plain]
Saving to: '/etc/init.d/game-server'

     0K ..                                                    100% 19.5M=0s

2017-04-28 14:00:00 (19.5 MB/s) - '/etc/init.d/game-server' saved [2622/2622]

/etc/init.d/kcp-server Update successfully !!!
Update shell successfully !!!

Please Re-run ./install-game-server.sh update`

**Comment by clangcn** [comment]
之前脚本有错误，修正了，请更新脚本
