### ISSUE TITLE
游戏服务端 无法配置多多端口

### ISSUE THREAD

**Issue by hanxu12** [clangcn/game-server#7]
比如我想配置两个端口
{
    "server":"0.0.0.0",
    "local_port":1080,
    "timeout": 600,
    "method":"chacha20",
    "fast_open": true,
    "port_password":
    {
        "10000": "1234567"
        "10001": "123456"
    },
    "_comment":
    {
        "10000": "The server port comment"
        "10001": "The server port comment"
    }
}
但保存后 restart service

root@n0n:~# /etc/init.d/game-server restart
Stoping Game-Server(XiaoBao) (pid 28879)...  done
Starting Game-Server(XiaoBao)...start failed

我觉得我配置文件填的没问题吧..求解惑  谢谢

**Comment by clangcn** [comment]
前面的端口后面都要有英文逗号，最后一个端口不能有逗号
{
"server":"0.0.0.0",
"local_port":1080,
"timeout": 600,
"method":"chacha20",
"fast_open": true,
"port_password":
{
"10000": "1234567",
"10001": "123456"
},
"_comment":
{
"10000": "The server port comment",
"10001": "The server port comment"
}
}
