### ISSUE TITLE
提一个BUG  291 行  wget

### ISSUE THREAD

**Issue by wb94** [clangcn/game-server#8]
第291 行下面两个  wget   少了  --no-check-certificate   会报错。

下面是改好的

if [ "${Is_64bit}" == 'y' ] ; then
        if [ ! -s ${str_game_dir}/game-server ]; then
            if ! wget --no-check-certificate ${game_x64_download_url} -O ${str_game_dir}/game-server; then
                echo "Failed to download game-server file!"
                exit 1
            fi
        fi
    else
         if [ ! -s ${str_game_dir}/game-server ]; then
            if ! wget --no-check-certificate ${game_x86_download_url} -O ${str_game_dir}/game-server; then
                echo "Failed to download game-server file!"
                exit 1
            fi
        fi
    fi

**Comment by clangcn** [comment]
fixed
